### ISSUE TITLE
APP crashed when playing the piano for some seconds

### ISSUE THREAD

**Issue by darewealth** [tckmn/semitone#3]
### Describe the bug.
When I clicked on 'Piano' and click on the keys for some seconds the app crashed.

### Steps to reproduce.
* Launch the app.

* Clicked on the Piano.

* Then, click on keys for some seconds.

* And note the bug

### Expected Behaviour

I don't expect the app to crash when I play the piano 

### Screen recording
https://youtu.be/I8-7vc-M-Xk

### Devices and Versions):)
* Device: [Itel]

* Version [6.1]

* App version [1.0]

### Log
```05-08 06:44:51.216 26545 26545 E AndroidRuntime: FATAL EXCEPTION: main
05-08 06:44:51.216 26545 26545 E AndroidRuntime: Process: mn.tck.semitone, PID: 26545
05-08 06:44:51.216 26545 26545 E AndroidRuntime: java.lang.NoSuchMethodError: No virtual method replace(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; in class Ljava/util/HashMap; or its super classes (declaration of 'java.util.HashMap' appears in /system/framework/core-libart.jar)
05-08 06:44:51.216 26545 26545 E AndroidRuntime: 	at mn.tck.semitone.PianoView.onTouchEvent(PianoView.java:154)
05-08 06:44:51.216 26545 26545 E AndroidRuntime: 	at android.view.View.dispatchTouchEvent(View.java:9307)
05-08 06:44:51.216 26545 26545 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2561)
05-08 06:44:51.216 26545 26545 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2256)
05-08 06:44:51.216 26545 26545 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2561)
05-08 06:44:51.216 26545 26545 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2256)
05-08 06:44:51.216 26545 26545 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2561)
05-08 06:44:51.216 26545 26545 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2256)
05-08 06:44:51.216 26545 26545 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2561)
05-08 06:44:51.216 26545 26545 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2256)
05-08 06:44:51.216 26545 26545 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2561)
05-08 06:44:51.216 26545 26545 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2256)
05-08 06:44:51.216 26545 26545 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2561)
05-08 06:44:51.216 26545 26545 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2256)
05-08 06:44:51.216 26545 26545 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2561)
05-08 06:44:51.216 26545 26545 E AndroidRuntime: 	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2256)
05-08 06:44:51.216 26545 26545 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2419)
05-08 06:44:51.216 26545 26545 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1744)
05-08 06:44:51.216 26545 26545 E AndroidRuntime: 	at android.app.Activity.dispatchTouchEvent(Activity.java:2776)
05-08 06:44:51.216 26545 26545 E AndroidRuntime: 	at com.android.internal.policy.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2380)
05-08 06:44:51.216 26545 26545 E AndroidRuntime: 	at android.view.View.dispatchPointerEvent(View.java:9533)
05-08 06:44:51.216 26545 26545 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4230)
05-08 06:44:51.216 26545 26545 E AndroidRuntime: 	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4096)
05-08 06:44:51.216 26545 26545 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
05-08 06:44:51.216 26545 26545 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
05-08 06:44:51.216 26545 26545 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
05-08 06:44:51.216 26545 26545 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3787)
05-08 06:44:51.216 26545 26545 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
05-08 06:44:51.216 26545 26545 E AndroidRuntime: 	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3844)
05-08 06:44:51.216 26545 26545 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
05-08 06:44:51.216 26545 26545 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3695)
05-08 06:44:51.216 26545 26545 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3661)
05-08 06:44:51.216 26545 26545 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3669)
05-08 06:44:51.216 26545 26545 E AndroidRuntime: 	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3642)
05-08 06:44:51.216 26545 26545 E AndroidRuntime: 	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5922)
05-08 06:44:51.216 26545 26545 E AndroidRuntime: 	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5896)
05-08 06:44:51.216 26545 26545 E AndroidRuntime: 	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5857)
05-08 06:44:51.216 26545 26545 E AndroidRuntime: 	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6025)
05-08 06:44:51.216 26545 26545 E AndroidRuntime: 	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
05-08 06:44:51.216 26545 26545 E AndroidRuntime: 	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
05-08 06:44:51.216 26545 26545 E AndroidRuntime: 	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
05-08 06:44:51.216 26545 26545 E AndroidRuntime: 	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:5996)
05-08 06:44:51.216 26545 26545 E AndroidRuntime: 	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:6048)
05-08 06:44:51.216 26545 26545 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
05-08 06:44:51.216 26545 26545 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:670)
05-08 06:44:51.216 26545 26545 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:600)
05-08 06:44:51.216 26545 26545 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
05-08 06:44:51.216 26545 26545 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:739)
05-08 06:44:51.216 26545 26545 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:95)
05-08 06:44:51.216 26545 26545 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
05-08 06:44:51.216 26545 26545 E AndroidRuntime: 	at android.app.ActivityThread```

**Comment by tckmn** [comment]
Thanks for the detailed bug report! This will be fixed in the next update.
